name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch (update as needed)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # Use the stable version of Flutter

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Build Flutter web app
    - name: Build Flutter web app
      run: flutter build web --release

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
