name: Flutter Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Check out repository
      uses: actions/checkout@v3

    # Setup Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5' # Use the stable version of Flutter

    # Get dependencies
    - name: Get dependencies
      run: flutter pub get

    # Run unit tests
    - name: Run unit tests
      run: flutter test
